name: Release Container
on:
  push:
    tags:
      - v*
env:
  IMAGE_NAME: godot4-omnibuilder3d
jobs:
  determine_version:
    uses: ./.github/workflows/determine-version.yml

  build_image:
    strategy:
      matrix:
        include:
          - godot_version: 4.4
            release_name: stable
          - godot_version: 4.4.1
            release_name: stable
    needs: determine_version
    uses: ./.github/workflows/build-image.yml
    with:
      sem_ver: ${{ needs.determine_version.outputs.sem_ver }}
      godot_version: ${{ matrix.godot_version }}
      release_name: ${{ matrix.release_name }}
      release_image: true
    secrets: inherit
  update_dockerhub_readme:
    name: Update Docker hub documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Write repo owner
        id: write_image_owner
        run: echo IMAGE_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}